### ISSUE TITLE
load a sample phenotype file issue

### ISSUE THREAD

**Issue by Chase556677** [amkusmec/FarmCPUpp#1]
After the installation according to your user guide, I tried to use the code below to load a sample  phenotype file.

> myY <- read.table(system.file("extdata", "YLD.txt",package = "FarmCPUpp"), header = TRUE, stringsAsFactors = FALSE)

It showed that 

Error in read.table(system.file("extdata", "YLD.txt", package = "FarmCPUpp"),  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

Plsease Help.Thanks

**Comment by amkusmec** [comment]
The sample phenotype file included with the package is called "mdp_traits_validation.txt".

If the file you're trying to load is your own, then you can leave out the entire `system.file()` call and put your file name into `read.table()` as normal.

**Comment by Chase556677** [comment]
It works.Thank you very much.
