### ISSUE TITLE
  installation of package had non-zero exit status

### ISSUE THREAD

**Issue by kshitiz52** [amkusmec/FarmCPUpp#3]
Warning in i.p(...) :
  installation of package ‘C:/Users/XXXXX/AppData/Local/Temp/RtmpEJpgQZ/file2e243e1f694e/FarmCPUpp_1.2.0.tar.gz’ had non-zero exit status

**Comment by amkusmec** [comment]
Please provide (1) the output of a call to `sessionInfo` and (2) the messages generated during installation. I cannot diagnose any problems without that information.

**Comment by kshitiz52** [comment]
1. > sessionInfo
function (package = NULL) 
{
    z <- list()
    z$R.version <- R.Version()
    z$platform <- z$R.version$platform
    if (nzchar(.Platform$r_arch)) 
        z$platform <- paste(z$platform, .Platform$r_arch, sep = "/")
    z$platform <- paste0(z$platform, " (", 8 * .Machine$sizeof.pointer, 
        "-bit)")
    z$locale <- Sys.getlocale()
    z$running <- osVersion
    z$RNGkind <- RNGkind()
    if (is.null(package)) {
        package <- grep("^package:", search(), value = TRUE)
        keep <- vapply(package, function(x) x == "package:base" || 
            !is.null(attr(as.environment(x), "path")), 
            NA)
        package <- .rmpkg(package[keep])
    }
    pkgDesc <- lapply(package, packageDescription, encoding = NA)
    if (length(package) == 0) 
        stop("no valid packages were specified")
    basePkgs <- sapply(pkgDesc, function(x) !is.null(x$Priority) && 
        x$Priority == "base")
    z$basePkgs <- package[basePkgs]
    if (any(!basePkgs)) {
        z$otherPkgs <- pkgDesc[!basePkgs]
        names(z$otherPkgs) <- package[!basePkgs]
    }
    loadedOnly <- loadedNamespaces()
    loadedOnly <- loadedOnly[!(loadedOnly %in% package)]
    if (length(loadedOnly)) {
        names(loadedOnly) <- loadedOnly
        pkgDesc <- c(pkgDesc, lapply(loadedOnly, packageDescription))
        z$loadedOnly <- pkgDesc[loadedOnly]
    }
    z$matprod <- as.character(options("matprod"))
    es <- extSoftVersion()
    z$BLAS <- as.character(es["BLAS"])
    z$LAPACK <- La_library()
    l10n <- l10n_info()
    if (!is.null(l10n["system.codepage"])) 
        z$system.codepage <- as.character(l10n["system.codepage"])
    if (!is.null(l10n["codepage"])) 
        z$codepage <- as.character(l10n["codepage"])
    class(z) <- "sessionInfo"
    z
}
<bytecode: 0x000001c77875b9a0>
<environment: namespace:utils>


2. make: *** [C:/PROGRA~1/R/R-41~1.0/etc/i386/Makeconf:245: QuickLM.o] Error 1
ERROR: compilation failed for package 'FarmCPUpp'
* removing 'C:/Users/XXXXX/Documents/R/win-library/4.1/FarmCPUpp'
Warning in i.p(...) :
  installation of package ‘C:/Users/XXXXX/AppData/Local/Temp/RtmpEJpgQZ/file2e241b2a69a2/FarmCPUpp_1.2.0.tar.gz’ had non-zero exit status

**Comment by amkusmec** [comment]
FYI you need to call `sessionInfo`: `sessionInfo()` with the parentheses.

It looks like you're running Windows. FarmCPUpp does not install properly on Windows. You'll need to use MacOS or Linux instead.
