### ISSUE TITLE
ERROR: compilation failed for package 'FarmCPUpp'

### ISSUE THREAD

**Issue by lariver2** [amkusmec/FarmCPUpp#5]
I am having trouble installing this package in R studio 4.3 
ERROR: compilation failed for package 'FarmCPUpp'

Warning in install.packages :
  installation of package ‘F:/SNB_GS_project/2020_SNB/input_data/myFarmPCU/FarmCPUpp_1.2.0.tar.gz’ had non-zero exit status.
Do you have any suggestions?
Thank you

**Comment by amkusmec** [comment]
To give any suggestions I'll need the complete installation text, which will include any errors that were generated. Copying and pasting the red text generated by the installation should include information on the specific error(s) that occurred.

**Comment by lariver2** [comment]
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:836:49:   required from 'void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Matrix<double, -1, -1>; Src = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; Func = assign_op<double, double>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h:732:41:   required from 'Derived& Eigen::PlainObjectBase<Derived>::_set_noalias(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; Derived = Eigen::Matrix<double, -1, -1>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h:818:25:   required from 'void Eigen::PlainObjectBase<Derived>::_init1(const Eigen::DenseBase<ElseDerived>&) [with T = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; OtherDerived = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; Derived = Eigen::Matrix<double, -1, -1>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/Matrix.h:294:31:   required from 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; _Scalar = double; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]'
QuickLM.cpp:90:32:   required from here
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:989:54: warning: ignoring attributes on template argument 'Eigen::internal::packet_traits<double>::type' {aka '__m128d'} [-Wignored-attributes]
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h: In instantiation of 'struct Eigen::internal::evaluator<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, 1, false> >':
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:736:20:   required from 'void Eigen::internal::call_dense_assignment_loop(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, 1, false>; SrcXprType = Eigen::CwiseBinaryOp<scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> >, const Eigen::Block<const Eigen::Block<const Eigen::Map<const Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>, -1, 1, false> >; Functor = add_assign_op<double, double>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:879:31:   required from 'static void Eigen::internal::Assignment<DstXprType, SrcXprType, Functor, Eigen::internal::Dense2Dense, Weak>::run(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, 1, false>; SrcXprType = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> >, const Eigen::Block<const Eigen::Block<const Eigen::Map<const Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>, -1, 1, false> >; Functor = Eigen::internal::add_assign_op<double, double>; Weak = void]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:836:49:   required from 'void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, 1, false>; Src = Eigen::CwiseBinaryOp<scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> >, const Eigen::Block<const Eigen::Block<const Eigen::Map<const Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>, -1, 1, false> >; Func = add_assign_op<double, double>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:804:27:   required from 'void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename enable_if<(! evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, 1, false>; Src = Eigen::CwiseBinaryOp<scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> >, const Eigen::Block<const Eigen::Block<const Eigen::Map<const Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>, -1, 1, false> >; Func = add_assign_op<double, double>; typename enable_if<(! evaluator_assume_aliasing<Src>::value), void*>::type = void*; typename evaluator_traits<SrcXprType>::Shape = Eigen::DenseShape]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/CwiseBinaryOp.h:177:18:   required from 'Derived& Eigen::MatrixBase<Derived>::operator+=(const Eigen::MatrixBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1> >, const Eigen::Block<const Eigen::Block<const Eigen::Map<const Eigen::Matrix<double, -1, -1>, 0, Eigen::OuterStride<> >, -1, 1, true>, -1, 1, false> >; Derived = Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >, -1, 1, false>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/products/TriangularMatrixVector.h:66:28:   [ skipping 26 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/QR/ColPivHouseholderQR.h:623:9:   required from 'static void Eigen::internal::Assignment<DstXprType, Eigen::Inverse<Eigen::ColPivHouseholderQR<MatrixType> >, Eigen::internal::assign_op<typename DstXprType::Scalar, typename Eigen::ColPivHouseholderQR<MatrixType>::Scalar>, Eigen::internal::Dense2Dense>::run(DstXprType&, const SrcXprType&, const Eigen::internal::assign_op<typename DstXprType::Scalar, typename Eigen::ColPivHouseholderQR<MatrixType>::Scalar>&) [with DstXprType = Eigen::Matrix<double, -1, -1>; MatrixType = Eigen::Matrix<double, -1, -1>; SrcXprType = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; typename Eigen::ColPivHouseholderQR<MatrixType>::Scalar = double; typename DstXprType::Scalar = double]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:836:49:   required from 'void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Matrix<double, -1, -1>; Src = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; Func = assign_op<double, double>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h:732:41:   required from 'Derived& Eigen::PlainObjectBase<Derived>::_set_noalias(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; Derived = Eigen::Matrix<double, -1, -1>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h:818:25:   required from 'void Eigen::PlainObjectBase<Derived>::_init1(const Eigen::DenseBase<ElseDerived>&) [with T = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; OtherDerived = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; Derived = Eigen::Matrix<double, -1, -1>]'
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/Matrix.h:294:31:   required from 'Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = Eigen::Inverse<Eigen::ColPivHouseholderQR<Eigen::Matrix<double, -1, -1> > >; _Scalar = double; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]'
QuickLM.cpp:90:32:   required from here
C:/Users/lariver2/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:989:54: warning: ignoring attributes on template argument 'Eigen::internal::packet_traits<double>::type' {aka '__m128d'} [-Wignored-attributes]
make: *** [C:/PROGRA~1/R/R-43~1.0/etc/x64/Makeconf:272: QuickLM.o] Error 1
ERROR: compilation failed for package 'FarmCPUpp'
* removing 'C:/Users/lariver2/AppData/Local/R/win-library/4.3/FarmCPUpp'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/lariver2/AppData/Local/Temp/RtmpMxdpx0/file2e7cbb476b5/FarmCPUpp_1.2.0.tar.gz’ had non-zero exit status

**Comment by amkusmec** [comment]
A few suggestions, none of them simple fixes:

1. Generally, FarmCPUpp has numerous, complex installation errors on Windows. `bigmemory`, which enables parallelization of the genotype matrix, does not play well with PCs. A simple fix is to move to a different OS. Any Unix-like should be sufficient.
2. The current release was last built on R 3.6.0. Until now I haven't received any reports of installation errors. That said, the error appears to be coming from the dependency `RcppEigen` and not FarmCPUpp per se. The last clean build I have used `RcppEigen` 0.3.3.5.0. The underlying C++ header files (linking to Eigen 3.4) have not changed between 0.3.3.5.0 and the current release (0.3.3.9.0) as near as I can tell from (1) the Eigen documentation and (2) the RcppEigen release notes. There appears to be an internal issue with pre-defined matrix types. One possible solution would be to manually install an older version of `RcppEigen` (preferably 0.3.3.5.0).

Neither of those solutions may be palatable, but they are the best options I can give at the present. As near as I can tell, this is an issue internal to the latest release of `RcppEigen` and not something I can fix. Sorry.

**Comment by lariver2** [comment]
Thank you for you answer. I am using R 3.6.0 and RcppEIgen 0.3.3.5.0 and I get this new error:
* installing *source* package 'FarmCPUpp' ...
** using staged installation
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/lariver2/Documents/R/win-library/3.6/bigmemory/include" -I"C:/Users/lariver2/Documents/R/win-library/3.6/BH/include" -I"C:/Users/lariver2/Documents/R/win-library/3.6/Rcpp/include" -I"C:/Users/lariver2/Documents/R/win-library/3.6/RcppEigen/include" -I"C:/Users/lariver2/Documents/R/win-library/3.6/RcppParallel/include"     -DRCPP_PARALLEL_USE_TBB=1   -O2 -Wall  -mtune=generic -c QuickLM.cpp -o QuickLM.o
In file included from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/cwchar:44:0,
                 from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/bits/postypes.h:40,
                 from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/bits/char_traits.h:40,
                 from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/string:40,
                 from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/stdexcept:39,
                 from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/array:38,
                 from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/tuple:39,
                 from C:/RBuildTools/3.5/mingw_32/i686-w64-mingw32/include/c++/unordered_map:41,
                 from C:/Users/lariver2/Documents/R/win-library/3.6/Rcpp/include/Rcpp/platform/compiler.h:153,
                 from C:/Users/lariver2/Documents/R/win-library/3.6/Rcpp/include/Rcpp/r/headers.h:62,
                 from C:/Users/lariver2/Documents/R/win-library/3.6/Rcpp/include/RcppCommon.h:30,
                 from C:/Users/lariver2/Documents/R/win-library/3.6/Rcpp/include/Rcpp.h:27,
                 from QuickLM.cpp:1:
QuickLM.cpp:58:19: error: declaration of '_imp___iob' as array of references
   RVector<double> stderr;
                   ^
QuickLM.cpp:64:62: error: declaration of '_imp___iob' as array of references
      const int df, NumericVector coefficients, NumericVector stderr,
                                                              ^
QuickLM.cpp:64:68: error: expected ')' before ',' token
      const int df, NumericVector coefficients, NumericVector stderr,
                                                                    ^
QuickLM.cpp:65:6: error: expected ';' at end of member declaration
      NumericMatrix seqQTN)
      ^
QuickLM.cpp:65:20: error: 'seqQTN' does not name a type
      NumericMatrix seqQTN)
                    ^
QuickLM.cpp: In member function 'virtual void LM::operator()(std::size_t, std::size_t)':
QuickLM.cpp:131:19: error: no match for 'operator=' (operand types are 'FILE {aka _iobuf}' and 'double')
         stderr[i] = ::NA_REAL;

**Comment by amkusmec** [comment]
That's the issue with Windows that I mentioned before. Something in the `RcppParallel` package doesn't play nice with the mingw compiler. It's not obvious what the issue is, and I don't have a PC to test it myself. That's why I recommend a Unix-like.

**Comment by lariver2** [comment]
Ok. Thank you. I am just going to drop it.
I can use other packages. Thank you!
